### PR TITLE
linux-5.3: adding vendor command policy

### PR DESCRIPTION
**Pull request by CGarces**
Required changes for kernel (>= 5.3.0), see torvalds/linux@901bb98.
Travis CI updated to last mainline and LTS kernel

### CODE REVIEW

**Review by FFY00 — APPROVED** [review]

**Comment by CGarces** [comment]
Hi @FFY00 why are you a reviewer? it's something in the github repo configuration?

**Comment by FFY00** [comment]
No, I don't have any permissions to the repo. I can still make reviews, they just aren't taken into account by the merge rules, which this repo doesn't actually have. I just left the review as a LGTM.

**Comment by CGarces** [comment]
Thanks @FFY00 , you have a rtl8192eu device?

**Comment by FFY00** [comment]
I do however it's not on me right now, so I didn't test the patch. I did however look a the patch and the new changes in linux 5.3, and it all looks fine to me.

**Comment by CGarces** [comment]
Squashed and merged, I don't know why the PR show 4 commits.

**Comment by tester1969** [comment]
Doesn't work for me, depmod/modprobe hangs... tried both Mange and CGarces

**Pull request merged**
