### PR TITLE
Updrade to version v5.6.4

### PR DESCRIPTION
**Pull request by CGarces**
This PR update the driver to the version v5.6.4 from Realtek
The main purpose of this PR is solve the issue #146 

Changelog since version v4.4.1_17696

- v4.4.1.1_18873.20160805
    - Update efuse write feature
    - add efuse update, efuse_file feature
    - add Rx signal Test feature
- v5.2.7_22739.20170615
    - Support Android 7.0
    - Support NAPI GRO
    - Update BT coexist to v46
    - Update adaptivity for new ETSI spec. (CE-RED)
    - Update FW to v35.1
    - Update PHY parameters v58
- v5.2.19_24763.20171030
    - Update FW to v35.6
    - Update Phydm to v021
    - Fix MP issue
    - Fixed WPA2 vulnerability - key reinstallation attacks(KRACKs)
- v5.2.19.1_25633.2017122
    - Update FW to v35.7
    - Update BT coexist to v47
    - Support Android 8.0
- v5.3.2_27210.20180604
    - Support 802.11s Mesh
- v5.6.3_31020.20181220
    - Support Linux Kernel 4.17
    - Support Android 9.x
    - Update PHYDM to v33
- v5.6.3.1_34030.20190613
    - Support WPA3-Personal (STA and softAP)
    - Fix IPS and LPS issues
- v5.6.4_35685.20191108
    - Fix WPA3 related bug
    - Hotfix P2P NoA buffer potentially overflow

The source code is the original from v5.6.4 but keeping some modifications from previous PR.

- #141
- #125
- #119
- #110
- #107
- #98 

And all the modifications of `os_dep/linux/usb_intf.c` to add new devices.

### CODE REVIEW

**Comment by CGarces** [comment]
Ping @mbuzdalov  
Your changes from #136 are lost, I don't know how apply them or if they are necessary.

**Comment by mbuzdalov** [comment]
Thanks for letting me know, I'll look at it when I have time. Until then, please just merge this PR, it has plenty of changes anyway.

**Comment by yavincl** [comment]
Wonder if this can fix https://github.com/Mange/rtl8192eu-linux-driver/issues/150

However, I can't find a updated version of this driver that will compile.

**Comment by kimocoder** [comment]
v5.6.4 is latest :+1: 
Checked Realtek ftp

Screenshot_20191119-230717

**Comment by CGarces** [comment]
Good to see you there @kimocoder 
Are you planning lo mantain also rtl8192eu?

**Comment by yavincl** [comment]
Does this compile?

**Comment by kimocoder** [comment]
Aaah no I don't have time for that 😏

**Comment by CGarces** [comment]
> Does this compile?

Not compiles for you? that is strange, try to reproduce the error and open an issue.

Each PR is tested in a automated way. 
You can check the logs in the commit history of the branch, there is a green tick (or red if fails)
The last logs, from this merge:
https://travis-ci.org/Mange/rtl8192eu-linux-driver/builds/614279207?utm_source=github_status&utm_medium=notification

**Comment by yavincl** [comment]
Nevermind, it does compile just fine.

**Pull request merged**
