### PR TITLE
Updated to v4.4.1

### PR DESCRIPTION
**Pull request by CGarces**
Updated to v4.4.1 from realtek

### CODE REVIEW

**Comment by CGarces** [comment]
@Mange Please don't merge yet, Git is marking some conflicts hand not made send for me (like makefile or readme) I need to review the cherry-picks used.

**Comment by CGarces** [comment]
I have fixed some commits, but can't not be merged with git.
Git is trying to merge the code from booth branches instead of just replace the code with the last branch.
The result is inconsistent and I think that will not work.
I recommend create a empty new branch (or one with 1387cf623d54bc2caec533e72ee18ef3b6a1db29)vand made the PR again

**Comment by Mange** [comment]
I'm unsure how to deal with this.

On one hand, if there's a newer version of the base drivers we should probably base everything on that and scrap current `master`.

On the other hand, I have no idea if that would lead to some hardware configurations not working anymore or if the upstream changes really are better than the community changes.

On the third hand, trying to rebase and make everything work on the same branch is very error prone as I would not know if anything worked or not after I fixed the conflicts.

As I'm not a C developer and I don't have the hardware in place (and frankly don't care enough about this to acquire or testing it either) so I have no good idea on how to evaluate the different choices here.

---

I'm leaning towards accepting this as a new branch, like you originally suggested, and to make that branch the default branch of the project. Then the README could mention the different branches.

Do you have any extra thoughts on this?

**Comment by CGarces** [comment]
I think that a new branch is the best solution.

**Comment by Mange** [comment]
I've pushed a new branch called `realtek-4.4.x` now with this commit history in it. I've also added you as a contributor with commit access (in case you want to add more fixes, strictly optional) and made that branch the default.

Thank you for all your work!

**Pull request closed without merging**
