### PR TITLE
Fix compilation with Kernel 4.15

### PR DESCRIPTION
**Pull request by CGarces**
Fix the code after API changes on 4.15

It's not a trivial change so I need someone with one rtl8192eu device to confirm that works as expected before merge.

Ping @masterzorag @gilcu3 @nomadmzl

### CODE REVIEW

**Comment by masterzorag** [comment]
Acknowledged, I have the hardware dongle to test in next days

**Comment by CGarces** [comment]
I have used a diferent aproach from https://github.com/jwrdegoede/rtl8189ES_linux/commit/8c3acf92759861e82b552b1f0ef1a26b26391071

The patch is ready to go, but I need some feedback from users with real hardware.

Ping @masterzorag @gilcu3 @nomadmzl

**Comment by MilhouseVH** [comment]
This updated driver (including this PR) is in [4.15-rc based LibreELEC builds](https://github.com/LibreELEC/LibreELEC.tv/pull/2275) but needs testing with real hardware. Anyone able to test and hopefully this change can be merged?

**Comment by demmm** [comment]
Patch tested & working on linux 4.15-rc8, build used:
https://github.com/KaOSx/main/commit/cbe86b0db7ab37dae8323caad5e5190a010307e1#diff-f3e97c058a52aa2d2a42437252fe4d7eR18
Compiler is gcc 6.4.0
Hardware tested:
```
lsusb | grep RTL
Bus 001 Device 002: ID 0bda:818b Realtek Semiconductor Corp. RTL8192EU 802.11b/g/n WLAN Adapter
```
```
lsmod | grep 81
8192eu               1052672  0
cfg80211              524288  1 8192eu
kvm_amd                81920  0
r8169                  77824  0
mii                    16384  1 r8169
usbcore               208896  8 usbhid,ehci_hcd,8192eu,ohci_pci,xhci_pci,ohci_hcd,xhci_hcd,ehci_pci
```

**Comment by CGarces** [comment]
Merged based on @demmm feedback

**Comment by M3rsy** [comment]
I try with kernerl 4.15.56 on slackware  , and  my error is that dont load the module

**Pull request merged**
