### PR TITLE
fix: Waddress

### PR DESCRIPTION
**Pull request by kmlebedev**
https://github.com/Mange/rtl8192eu-linux-driver/issues/297

### CODE REVIEW

**Comment by CGarces** [comment]
Thanks for your PR.
Please use this as reference
https://github.com/cilynx/rtl88x2bu/commit/2b4f8e94c65c302d9739d4a86afee1a160d9fed3

use `dvobj->padapters[i]` as replacement instead of remove it.
It's the approach user by the vendor driver in the last version (v5.11.2.1)
https://github.com/CGarces/rtl8192eu-linux-driver/blob/3cd41fedd2370019f6563938a7d0227c93e98e30/core/rtw_ap.c#L4422

Also ¿remove the memcpy is safe?

**Comment by kmlebedev** [comment]
> Thanks for your PR. Please use this as reference [cilynx/rtl88x2bu@2b4f8e9](https://github.com/cilynx/rtl88x2bu/commit/2b4f8e94c65c302d9739d4a86afee1a160d9fed3)
> 
> use `dvobj->padapters[i]` as replacement instead of remove it. It's the approach user by the vendor driver in the last version (v5.11.2.1) https://github.com/CGarces/rtl8192eu-linux-driver/blob/3cd41fedd2370019f6563938a7d0227c93e98e30/core/rtw_ap.c#L4422
> 
> Also ¿remove the memcpy is safe?



> Thanks for your PR. Please use this as reference [cilynx/rtl88x2bu@2b4f8e9](https://github.com/cilynx/rtl88x2bu/commit/2b4f8e94c65c302d9739d4a86afee1a160d9fed3)
> 
> use `dvobj->padapters[i]` as replacement instead of remove it. It's the approach user by the vendor driver in the last version (v5.11.2.1) https://github.com/CGarces/rtl8192eu-linux-driver/blob/3cd41fedd2370019f6563938a7d0227c93e98e30/core/rtw_ap.c#L4422
> 

Thanks for the links. Since I wanted to quickly assemble it, I fixed it in a frenzy

> Also ¿remove the memcpy is safe?

It seems yes in the work of Wi-Fi problems have not yet been noticed

**Comment by kmlebedev** [comment]
@CGarces Done and tested

**Comment by CGarces** [comment]
Opps, I just forgot this PR.

**Comment by Mange** [comment]
I got an email about this PR and wanted to redirect the message here for the maintainers.

> In the attached image we see that `data_len` was changed to `tag->tag_len`. Previously we see:
> ```c
> data_len = tag->tag_len + TAG_HDR_LEN;
> ```
>
> And then a length check:
> ```c
> if (skb_tailroom(skb) < data_len) {
> ```
> 
> Then the buffer was moved forward by data_len to make space:
> ```c
> memmove(((unsigned char *)ph->tag + data_len), (unsigned char *)ph->tag, ntohs(ph->length));
> ```
>
> And the tag was copied to the new space in the original code:
> ```c
> memcpy((unsigned char *)ph->tag, tag, data_len);
> ```
>
> Clearly it doesn't make sense for the original buffer contents to remain at the interval [`tag->tag_len`, `data_len`).
>
> Moreover, I was wondering if `tag->tag_len + TAG_HDR_LEN` can overflow, in which case the new code will crash.

Screenshot_20221221-083708

**Comment by CGarces** [comment]
Thanks @Mange I'll revert this change  and add also #303

**Pull request merged**
